version: '3'
services:

  redis:
    image: redis:latest

  mocked-ws:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/mocked-ws/Dockerfile
    command: python -u -m uvicorn --reload --host 0.0.0.0 --port 7455 mocked-ws.app.main:app
    volumes:
      - ./packages/mocked-ws:/app/mocked-ws
      - ../genworlds:/app/genworlds
      - ./use-cases:/app/use-cases

  real-ws:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/real-ws/Dockerfile
    command: python real-ws/main.py # 7456
    volumes:
      - ./packages/real-ws:/app/real-ws
      - ../genworlds:/app/genworlds

  world-instance:
    build:
      context: ../
      dockerfile: ./genworlds-community/packages/world-instance/Dockerfile
    command: python -u -m uvicorn --reload --host 0.0.0.0 --port 7457 world-instance.main:app
    volumes:
      - ./packages/world-instance:/app/world-instance
      - ../genworlds:/app/genworlds
      - ./use-cases:/app/use-cases
    depends_on:
      - real-ws

  # 16bit-back:
  #   build: packages/16bit-back
  #   command: ts-node-dev --respawn --transpile-only src/server.ts
  #   volumes:
  #     - ./packages/16bit-back:/app
  #   depends_on:
  #     - real-ws
  #     - mocked-ws
  #     - redis

  # 16bit-front:
  #   build: packages/16bit-front
  #   command: yarn serve
  #   volumes:
  #     - ./16bit-front:/app
  #   depends_on:
  #     - 16bit-back

  # nano-vue:
  #   build: packages/nano-vue
  #   command: yarn serve
  #   volumes:
  #     - ./packages/nano-vue:/app
  #   depends_on:
  #     - 16bit-front
  #   ports:
  #     - "8080:8080"

  # gateway:
  #   build: packages/gateway
  #   command: node --inspect-brk=0.0.0.0 src/server.js
  #   volumes:
  #     - ./packages/gateway:/app
  #   depends_on:
  #     - nano-vue
  #   ports:
  #     - "9000:9000"
  #     - "9229:9229"