version: '3.8'

services:
  vue-frontend:
    build:
      context: .
      dockerfile: ./docker/nano-vue.Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - world-instance
      - real-ws
      - mocked-ws
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  world-instance:
    build:
      context: .
      dockerfile: ./docker/world-instance.Dockerfile
    ports:
      - "7457:7457"
      - "5678:5678"
    depends_on:
      - real-ws
      - mocked-ws
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  real-ws:
    build:
      context: .
      dockerfile: ./docker/real-ws.Dockerfile
    ports:
      - "7456:7456"
      - "5679:5679"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mocked-ws:
    build:
      context: .
      dockerfile: ./docker/mocked-ws.Dockerfile
    ports:
      - "7455:7455"
      - "5680:5680"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redisdb:
    image: redis:7-alpine
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  16bit-back:
    build:
      context: ./
      dockerfile: ./docker/16bit-back.Dockerfile
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redisdb
      - mocked-ws
    environment:
      NODE_ENV: "production"
      LOGGING_LEVEL: "debug"
      SERVER_PORT: "5000"
      SERVER_LOGGING_ACCESS: "true"
      SERVER_LOGGING_ERRORS: "true"
      SERVER_LOGGING_STACKTRACE: "true"
      SERVER_CORS_ORIGINS: ""
      AUTH_SECRET_KEY: "thisHaveToBeChanged!"
      DB_REDIS_HOST: "redisdb"
      DB_REDIS_PORT: "6379"
      DB_REDIS_PREFIX: ""
      YEAGER_WORLD_WS_HOST: "ws://mocked-ws"
      YEAGER_WORLD_WS_PORT: "7455"
      YEAGER_WORLD_WS_PATH: "ws"
    ports:
      - "5000:5000"
