version: "3.7"

services:
  mongodb:
    image: mongo:6
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MONGO_INITDB_ROOT_USERNAME: some_user
      MONGO_INITDB_ROOT_PASSWORD: some_pass

  redisdb:
    image: redis:7-alpine
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  server:
    build:
      context: ./
      dockerfile: ./docker/prod.Dockerfile
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mongodb
      - redisdb
      - mockedworld
    env_file:
      - ./env/test.env
    environment:
      LOGGING_LEVEL: "info"
      SERVER_PORT: "5000"
      DB_MONGO_HOST: "mongodb"
      DB_MONGO_PORT: "27017"
      DB_MONGO_USER: "some_user"
      DB_MONGO_PASS: "some_pass"
      DB_REDIS_HOST: "redisdb"
      DB_REDIS_PORT: "6379"
      YEAGER_WORLD_WS_PORT: "5001"
      YEAGER_WORLD_WS_HOST: "mockedworld"
    ports:
      - "5000:5000"

  mockedworld:
    build:
      context: ./
      dockerfile: ./docker/prod.Dockerfile
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mongodb
      - redisdb
    env_file:
      - ./env/test.env
    environment:
      LOGGING_LEVEL: "info"
      YEAGER_WORLD_WS_PORT: "5001"
    command: ["node", "./src/mocks/worldWs.js"]
