version: '3'
services:

  redis:
    image: redis:latest

  mocked-ws:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/mocked-ws/Dockerfile
    command: /bin/bash -c "pip install -e /app/genworlds && python -u -m uvicorn --reload --host 0.0.0.0 --port 7455 mocked-ws.app.main:app"
    volumes:
      - ./packages/mocked-ws:/app/mocked-ws
      - ../genworlds:/app/genworlds
      - ./use_cases:/app/use_cases

  real-ws:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/real-ws/Dockerfile
    command: /bin/bash -c "pip install -e /app/genworlds && python real-ws/main.py" # 7456
    volumes:
      - ./packages/real-ws:/app/real-ws
      - ../genworlds:/app/genworlds

  world-instance:
    build:
      context: ../
      dockerfile: ./genworlds-community/packages/world-instance/Dockerfile
    environment:
      - VUE_APP_IS_DEV=true
    command: /bin/bash -c "pip install -e /app/genworlds && python -u -m uvicorn --reload --host 0.0.0.0 --port 7457 world-instance.main:app"
    volumes:
      - ./packages/world-instance:/app/world-instance
      - ../genworlds:/app/genworlds
      - ./use_cases:/app/use_cases
    depends_on:
      - real-ws

  16bit-back:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/16bit-back/Dockerfile
    environment:
      - VUE_APP_IS_DEV=true
    command: /home/node/app/node_modules/.bin/ts-node-dev --respawn --transpile-only src/server.ts
    volumes:
      - ./packages/16bit-back:/app
    depends_on:
      - real-ws
      - mocked-ws
      - redis

  16bit-front:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/16bit-front/Dockerfile
    environment:
      - VUE_APP_IS_DEV=true
    command: ["/bin/sh", "-c", "yarn install && yarn dev"]
    volumes:
      - ./packages/16bit-front:/app
      - /app/node_modules
    depends_on:
      - 16bit-back

  nano-vue:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/nano-vue/Dockerfile
    environment:
      - VUE_APP_IS_DEV=true
    command: yarn serve
    volumes:
      - ./packages/nano-vue:/app
    depends_on:
      - 16bit-front
    ports:
      - "8080:8080"

  gateway:
    build: 
      context: ../
      dockerfile: ./genworlds-community/packages/gateway/Dockerfile
    environment:
      - VUE_APP_IS_DEV=true
    command: node server.js
    volumes:
      - ./packages/gateway:/app
    depends_on:
      - nano-vue
    ports:
      - "9000:9000"